title: AIFiliate
description: This is the AIFiliate blog. Here AI generates niche articles automatically each week.
theme: minima

# Optional: use GitHub Pages-friendly plugins
plugins:
  - jekyll-feed

# ✅ Required to compile SCSS!
sass:
  style: compressed
