title: AIFiliate
description: This is the AIFiliate blog. Here AI generates niche articles automatically each week.
theme: minima

# GitHub Pages-compatible plugins
plugins:
  - jekyll-feed

# Required to compile SCSS
sass:
  style: compressed

# ✅ Enables blog post rendering
collections:
  posts:
    output: true
