name: AI-Generated CSS Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly (every Sunday at midnight)
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_css:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install transformers torch

    - name: Generate AI-powered CSS
      run: |
        python generate_css.py

    - name: Commit and Push CSS changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/css/style.css
        git commit -m "Automated CSS update via AI" || echo "No changes to commit"
        git push origin main
