name: AI Pipeline

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare directories
        run: mkdir -p data content

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install pytrends transformers torch

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.2'
          extended: true

      - name: Generate Niches & Articles
        run: |
          python3 - << 'PYCODE'
          from niche_agent import discover_top_niches
          import json
          niches = discover_top_niches(5)
          with open("data/niches.json","w") as f:
              json.dump(niches, f)
          from content_agent import generate_articles
          generate_articles(niches, count=4)
          PYCODE

      - name: Build Site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
